# version: '3.8' oboslete for debian 
# is the test .sh executable and fix
services:
# NGINX
  nginx:
    env_file:
      - ./.env
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: nginx-Dockerfile
      args:
        BASE_VERSION: ${BASE_VERSION}
        CRT_PATH: ${CRT_PATH}
        KEY_PATH: ${KEY_PATH}
        SECURE_PORT: ${SECURE_PORT}
    entrypoint: ["/entrypoint.sh"]
    ports:
      - "${SECURE_PORT}:${SECURE_PORT}"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CRT_PATH=${CRT_PATH}
      - KEY_PATH=${KEY_PATH}
      #- INSECURE_PORT=${INSECURE_PORT}
      - SECURE_PORT=${SECURE_PORT}
      - WORDPRESS_PORT=${WORDPRESS_PORT}

      #- CRT=${CRT}
      #- KEY=${KEY}

    volumes:
      #- ${VOLUME_PATH_GENERIC}nginx-selfsigned.crt:${CRT_PATH}
      #- ${VOLUME_PATH_GENERIC}nginx-selfsigned.key:${KEY_PATH}
#      - .${CRT_PATH}:${CRT_PATH}
#      - .${KEY_PATH}:${KEY_PATH}
      - ${WORDPRESS_VOLUME_PATH}:/var/www/html
      #- ${NGINX_VOLUME_PATH}nginx-logs:/var/log/nginx 
      #- /root/incept/inception/srcs/nginx_error.log:/var/log/nginx/error.log
      #- /root/incept/inception/srcs/nginx_access.log:/var/log/nginx/access.log
    networks:
      - inceptionnet
    restart: unless-stopped
    depends_on:
      - wordpress
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:${SECURE_PORT} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3


# WORDPRESS
  wordpress:
    env_file:
      - ./.env
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: wordpress-Dockerfile
      args:
        BASE_VERSION: ${BASE_VERSION}
        WORDPRESS_PORT: ${WORDPRESS_PORT}
    entrypoint: ["/entrypoint.sh"]
    #ports:
    environment:
      - WORDPRESS_DB_HOST=${DB_HOST}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_PORT=${WORDPRESS_PORT}
      - ADMIN_UNAME=${ADMIN_UNAME}
      - BOSS_PASS=${BOSS_PASS}
      - GUEST_UNAME=${GUEST_UNAME}
      - GUEST_PASS=${GUEST_PASS}
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ${WORDPRESS_VOLUME_PATH}:/var/www/html
    networks:
      - inceptionnet
    restart: unless-stopped
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://nginx/wp-admin/install.php || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
# MARIADB
  mariadb:
    env_file:
      - ./.env
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: mariadb-Dockerfile
      args:
        BASE_VERSION: ${BASE_VERSION}
        WORDPRESS_PORT: ${WORDPRESS_PORT}
        MARIADB_PORT: ${MARIADB_PORT}
    entrypoint: ["/entrypoint.sh"]
    environment:
      - DB_SYS_USER=${DB_SYS_USER}
      - BIND_ADDR=${BIND_ADDR}
      - DB_PIDFILE=${DB_PIDFILE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_PORT=${MARIADB_PORT}
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/mysql
    networks:
      - inceptionnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  wordpress-data:
  db-data:
networks:
  inceptionnet:
    driver: bridge
    name: inceptionnet
